### ISSUE TITLE
CSS and JS Files referenced by http not https like the rest of the site

### ISSUE THREAD

**Issue by wags007** [PureStorage-OpenConnect/pso-explorer-container#11]
I have deployed this on Kubernetes with an https ingress in front of the application.  The CSS and JS filed in subdirectories are blocked because of mixed-mode errors.  This seems to be because they are being referred to at, for instance,  http://psoexplorer.rancher.localhost/js/jquery.min.js instead of https://psoexplorer.rancher.localhost/js/jquery.min.js .

**Comment by dnix101** [comment]
@wags007 We've changed the links to relative links in the new release that we've just pushed. This should solve this issue. Can you test if this solves the issues for you?

**Comment by dnix101** [comment]
This issues was resolved in the latest release, the updated v0.5.5 helm chart and image tag v0.5.5a.
